#!/bin/bash

# async-parent: Asynchronous execution demo (parent)

echo "Parent: launching child script..."
async-child &
pid=$!
echo "Parent: child (PID=$pid) launched."

echo "Parent: continuing..."
sleep 2

echo "Parent: pausing to wait for chiild to finish..."
wait "$pid"

echo "Parent: child is finished. Continuing..."
echo "Parent: parent is done. Exiting."