#!/bin/bash

# while-menu: a menu driven system information program

DELAY=3		# Number of seconds to display results.

while [[ "$REPLY" != 0 ]]; do
	clear
	echo "
	Please Select:

	1. Display System Information
	2. Display Disk Space
	3. Display Home Space Utilization
	0. Quit
	"

	read -p "Enter selection [0-3] > "

	if [[ "$REPLY" =~ ^[0-3]$ ]]; then
		if [[ "$REPLY" == 0 ]]; then
			echo "Program terminated."
			exit
		fi
		if [[ "$REPLY" == 1  ]]; then
			echo "Hostname: $HOSTNAME"
			uptime
		fi
		if [[ "$REPLY" == 2 ]]; then
			df -h
		fi
		if [[ "$REPLY" == 3 ]]; then
			if [[ "$(id -u)" -eq 0 ]]; then
				echo "Home Space Utilization (All Users)"
				du -sh /home/*
			else
				echo "Home Space Utilization ($USER)"
				du -sh "$HOME" 2>/dev/null
			fi
		fi
	else
		echo "Invalid entry." >&2
		exit 1
	fi
	sleep "$DELAY"
done
echo "Program terminated.