#!/bin/bash

for x
do  
    echo "editing $x: \c"
    if [[ "$x" = "sedscr" ]]; then
        echo "not editing sedscr!"
    elif [ -s "$s" ]; then  # file exists and has a length greater than zero
        sed -f sedscr "$x" > /tmp/$x$$
        if [ -s "/tmp/$x$$" ]
        then 
            if cmp -s "$x" "/tmp/$x$$"
            then
                echo "file not changed: \c"
            else
                mv "$x" "$x.bak"    # save original, just in case
                cp "/tmp/$x$$" "$x"
            file
            echo "done"
        else
            echo "Sed produced an empty file\c"
            echo " - check your sedscript."
        fi
        rm -f "/tmp/$$$"
    else
        echo "original file is empty."
    fi
done
echo "all done"
